midline_node:
  ros__parameters:
    securityFactor: 2.0
    visualization: false
    separation: 4.0
    spacing: 0.05 # Distanza tra i punti creati nella midline

    Paths.midline: data/cones.csv
    Paths.save: data/